version: '2.28'

include:
  - ops/docker-compose.postgres.yml

services:
  bot:
    build: src/bot
    env_file: ./.env
    depends_on:
      - backend
  
  backend:
    build: src/api
    env_file: ./.env
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: 
      context: src/contact-app
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - ./.env

    ports:
      - "80:80"
    networks:
      - app-network


    
networks:
  app-network:
    driver: bridge