version: '2.28'

include:
  - ops/docker-compose.postgres.yml

services:
  bot:
    build: src/bot
    env_file: ./.env
    depends_on:
      - backend
  
  backend:
    build: src/api
    env_file: ./.env
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy


    
networks:
  app-network:
    driver: bridge