version: "2.28"

include:
  - ops/docker-compose.postgres.yml

services:
  edge-router:
    build: ops/edge-router
    container_name: edge-router
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    env_file:
      - ./.env
    environment:
      - DOMAIN_URL=${DOMAIN_URL}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    restart: unless-stopped

  bot:
    container_name: bot
    build: src/bot
    env_file: ./.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build: src/api
    env_file: ./.env
    expose:
      - 4000
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: src/contact-app
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - ./.env
    expose:
      - 80

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var: 
