version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    networks:
      - app_network
    restart: unless-stopped